trigger:
  branches:
    include:
      - main
      - refs/tags/*

schedules:
- cron: "0 3 * * *"
  displayName: Daily 3am (UTC) build
  branches:
    include:
    - main
    - benchmarks/*
  always: true

variables:
  buildConfiguration: release
  publishOutput: $(Build.SourcesDirectory)/src/bin/managed-publish

stages:
- stage: build
  jobs:

  #### Windows 

  - job: Windows
    pool: Benchmarks
    
    workspace:
      clean: all

    variables:
      tracerHomeName: windows-tracer-home
      tracerHome: $(System.DefaultWorkingDirectory)/src/bin/$(tracerHomeName)
      msiHome: $(System.DefaultWorkingDirectory)/src/bin/msi
      nuget_packages: $(Pipeline.Workspace)/.nuget/packages

    steps:

    - task: UseDotNet@2
      displayName: install dotnet core sdk
      inputs:
        packageType: sdk
        version: 5.0.x

    - task: NuGetToolInstaller@1
      displayName: install nuget

    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: restore
        projects: src/**/*.csproj

    # native projects must be restored with nuget.exe
    - task: NuGetCommand@2
      displayName: nuget restore native
      inputs:
        restoreSolution: Datadog.Trace.Native.sln
        verbosityRestore: Normal

    - task: DotNetCoreCLI@2
      displayName: Benchmarks
      inputs:
        command: 'run'
        projects: '$(System.DefaultWorkingDirectory)/test/benchmarks/Benchmarks.Trace/Benchmarks.Trace.csproj'
        arguments: '-c Release -f netcoreapp3.1 -- -r net472 netcoreapp3.1 -m -f * --iterationTime 1500'
      env:
        OTEL_ENV: CI
        OTEL_SERVICE: dd-trace-dotnet

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: 'Start-Sleep -s 120'