name: SdkVersionCheck

on:
  push:
    branches: [ main ]
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  check-sdk-versions:
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag: v4.2.2

      - name: Setup .NET 8
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee # tag: v4.0.1
        with:
          dotnet-version: 8.0.403

      - name: Run VerifySdkVersions
        run: ./build.cmd VerifySdkVersions
